bde:
  target: dev
  outputs:
    dev:
      database: postgres
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: airflow
      password: airflow
      schema: airbnb_raw